# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_control_panel.ui'
#
# Created: Mon Feb 22 19:29:43 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName(_fromUtf8("Panel"))
        Panel.resize(326, 593)
        self.gridLayout = QtGui.QGridLayout(Panel)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(Panel)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 11, 7, 1, 1)
        self.radioButton_roomT = QtGui.QRadioButton(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.radioButton_roomT.setFont(font)
        self.radioButton_roomT.setObjectName(_fromUtf8("radioButton_roomT"))
        self.gridLayout.addWidget(self.radioButton_roomT, 17, 3, 1, 4)
        self.label_temperature = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_temperature.setFont(font)
        self.label_temperature.setObjectName(_fromUtf8("label_temperature"))
        self.gridLayout.addWidget(self.label_temperature, 15, 0, 3, 3)
        self.pushButton_set_as_origin = QtGui.QPushButton(Panel)
        self.pushButton_set_as_origin.setObjectName(_fromUtf8("pushButton_set_as_origin"))
        self.gridLayout.addWidget(self.pushButton_set_as_origin, 9, 6, 1, 4)
        self.label_Y = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_Y.setFont(font)
        self.label_Y.setObjectName(_fromUtf8("label_Y"))
        self.gridLayout.addWidget(self.label_Y, 7, 0, 1, 1)
        self.label_11 = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 13, 0, 1, 10)
        self.label_Z = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_Z.setFont(font)
        self.label_Z.setObjectName(_fromUtf8("label_Z"))
        self.gridLayout.addWidget(self.label_Z, 9, 0, 1, 1)
        self.pushButton_activate = QtGui.QPushButton(Panel)
        self.pushButton_activate.setObjectName(_fromUtf8("pushButton_activate"))
        self.gridLayout.addWidget(self.pushButton_activate, 6, 6, 2, 4)
        self.spinBox_X = QtGui.QSpinBox(Panel)
        self.spinBox_X.setObjectName(_fromUtf8("spinBox_X"))
        self.gridLayout.addWidget(self.spinBox_X, 6, 1, 1, 1)
        self.label_X = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_X.setFont(font)
        self.label_X.setObjectName(_fromUtf8("label_X"))
        self.gridLayout.addWidget(self.label_X, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 10)
        self.label_wavemeter_readout = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_wavemeter_readout.setFont(font)
        self.label_wavemeter_readout.setObjectName(_fromUtf8("label_wavemeter_readout"))
        self.gridLayout.addWidget(self.label_wavemeter_readout, 4, 1, 1, 6)
        self.checkBox_wavemeter = QtGui.QCheckBox(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.checkBox_wavemeter.setFont(font)
        self.checkBox_wavemeter.setObjectName(_fromUtf8("checkBox_wavemeter"))
        self.gridLayout.addWidget(self.checkBox_wavemeter, 3, 1, 1, 6)
        self.dSBox_coarse_lambda_2 = QtGui.QDoubleSpinBox(Panel)
        self.dSBox_coarse_lambda_2.setObjectName(_fromUtf8("dSBox_coarse_lambda_2"))
        self.gridLayout.addWidget(self.dSBox_coarse_lambda_2, 2, 6, 1, 3)
        self.label_power = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_power.setFont(font)
        self.label_power.setObjectName(_fromUtf8("label_power"))
        self.gridLayout.addWidget(self.label_power, 2, 0, 1, 2)
        self.dSBox_coarse_lambda = QtGui.QDoubleSpinBox(Panel)
        self.dSBox_coarse_lambda.setObjectName(_fromUtf8("dSBox_coarse_lambda"))
        self.gridLayout.addWidget(self.dSBox_coarse_lambda, 1, 6, 1, 3)
        self.label_coarse_lambda = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_coarse_lambda.setFont(font)
        self.label_coarse_lambda.setObjectName(_fromUtf8("label_coarse_lambda"))
        self.gridLayout.addWidget(self.label_coarse_lambda, 1, 0, 1, 4)
        self.label = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.horizontalSlider_p1 = QtGui.QSlider(Panel)
        self.horizontalSlider_p1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_p1.setObjectName(_fromUtf8("horizontalSlider_p1"))
        self.gridLayout.addWidget(self.horizontalSlider_p1, 14, 0, 1, 7)
        self.doubleSpinBox_p1 = QtGui.QDoubleSpinBox(Panel)
        self.doubleSpinBox_p1.setObjectName(_fromUtf8("doubleSpinBox_p1"))
        self.gridLayout.addWidget(self.doubleSpinBox_p1, 14, 8, 1, 2)
        self.label_curr_pos_readout_z = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_readout_z.setFont(font)
        self.label_curr_pos_readout_z.setObjectName(_fromUtf8("label_curr_pos_readout_z"))
        self.gridLayout.addWidget(self.label_curr_pos_readout_z, 11, 8, 1, 1)
        self.spinBox_Y = QtGui.QSpinBox(Panel)
        self.spinBox_Y.setObjectName(_fromUtf8("spinBox_Y"))
        self.gridLayout.addWidget(self.spinBox_Y, 7, 1, 1, 1)
        self.spinBox_Z = QtGui.QSpinBox(Panel)
        self.spinBox_Z.setObjectName(_fromUtf8("spinBox_Z"))
        self.gridLayout.addWidget(self.spinBox_Z, 9, 1, 1, 1)
        self.label_curr_pos_readout_y = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_readout_y.setFont(font)
        self.label_curr_pos_readout_y.setObjectName(_fromUtf8("label_curr_pos_readout_y"))
        self.gridLayout.addWidget(self.label_curr_pos_readout_y, 11, 6, 1, 1)
        self.radioButton_lowT = QtGui.QRadioButton(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.radioButton_lowT.setFont(font)
        self.radioButton_lowT.setObjectName(_fromUtf8("radioButton_lowT"))
        self.gridLayout.addWidget(self.radioButton_lowT, 16, 3, 1, 2)
        self.label_2 = QtGui.QLabel(Panel)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 11, 5, 1, 1)
        self.label_curr_pos_readout_x = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_readout_x.setFont(font)
        self.label_curr_pos_readout_x.setObjectName(_fromUtf8("label_curr_pos_readout_x"))
        self.gridLayout.addWidget(self.label_curr_pos_readout_x, 11, 4, 1, 1)
        self.label_curr_pos_text = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_text.setFont(font)
        self.label_curr_pos_text.setObjectName(_fromUtf8("label_curr_pos_text"))
        self.gridLayout.addWidget(self.label_curr_pos_text, 11, 0, 1, 4)

        self.retranslateUi(Panel)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(_translate("Panel", "Panel", None))
        self.label_3.setText(_translate("Panel", ",", None))
        self.radioButton_roomT.setText(_translate("Panel", " room T", None))
        self.label_temperature.setText(_translate("Panel", "Temperature:", None))
        self.pushButton_set_as_origin.setText(_translate("Panel", "Set as origin", None))
        self.label_Y.setText(_translate("Panel", "Y", None))
        self.label_11.setText(_translate("Panel", "FINE POSITIONING", None))
        self.label_Z.setText(_translate("Panel", "Z", None))
        self.pushButton_activate.setText(_translate("Panel", "Activate", None))
        self.label_X.setText(_translate("Panel", "X", None))
        self.label_5.setText(_translate("Panel", "COARSE POSITIONING", None))
        self.label_wavemeter_readout.setText(_translate("Panel", "#########", None))
        self.checkBox_wavemeter.setText(_translate("Panel", "wavemeter", None))
        self.label_power.setText(_translate("Panel", "power level [mW]", None))
        self.label_coarse_lambda.setText(_translate("Panel", "coarse wavelength [nm]", None))
        self.label.setText(_translate("Panel", "LASER", None))
        self.label_curr_pos_readout_z.setText(_translate("Panel", "##", None))
        self.label_curr_pos_readout_y.setText(_translate("Panel", "##", None))
        self.radioButton_lowT.setText(_translate("Panel", " low T", None))
        self.label_2.setText(_translate("Panel", ",", None))
        self.label_curr_pos_readout_x.setText(_translate("Panel", "##", None))
        self.label_curr_pos_text.setText(_translate("Panel", "current position (x,y,z):", None))

