# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_control_panel.ui'
#
# Created: Fri Mar 25 18:07:02 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName(_fromUtf8("Panel"))
        Panel.resize(333, 683)
        self.label_3 = QtGui.QLabel(Panel)
        self.label_3.setGeometry(QtCore.QRect(140, 450, 16, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.radioButton_roomT = QtGui.QRadioButton(Panel)
        self.radioButton_roomT.setGeometry(QtCore.QRect(100, 650, 73, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.radioButton_roomT.setFont(font)
        self.radioButton_roomT.setObjectName(_fromUtf8("radioButton_roomT"))
        self.label_temperature = QtGui.QLabel(Panel)
        self.label_temperature.setGeometry(QtCore.QRect(10, 590, 151, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_temperature.setFont(font)
        self.label_temperature.setObjectName(_fromUtf8("label_temperature"))
        self.pushButton_set_as_origin = QtGui.QPushButton(Panel)
        self.pushButton_set_as_origin.setGeometry(QtCore.QRect(226, 360, 75, 23))
        self.pushButton_set_as_origin.setObjectName(_fromUtf8("pushButton_set_as_origin"))
        self.label_Y = QtGui.QLabel(Panel)
        self.label_Y.setGeometry(QtCore.QRect(38, 325, 16, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_Y.setFont(font)
        self.label_Y.setObjectName(_fromUtf8("label_Y"))
        self.label_11 = QtGui.QLabel(Panel)
        self.label_11.setGeometry(QtCore.QRect(10, 480, 162, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_Z = QtGui.QLabel(Panel)
        self.label_Z.setGeometry(QtCore.QRect(38, 357, 16, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_Z.setFont(font)
        self.label_Z.setObjectName(_fromUtf8("label_Z"))
        self.pushButton_activate = QtGui.QPushButton(Panel)
        self.pushButton_activate.setGeometry(QtCore.QRect(226, 312, 75, 23))
        self.pushButton_activate.setObjectName(_fromUtf8("pushButton_activate"))
        self.spinBox_X = QtGui.QSpinBox(Panel)
        self.spinBox_X.setGeometry(QtCore.QRect(90, 296, 51, 20))
        self.spinBox_X.setObjectName(_fromUtf8("spinBox_X"))
        self.label_X = QtGui.QLabel(Panel)
        self.label_X.setGeometry(QtCore.QRect(38, 293, 16, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_X.setFont(font)
        self.label_X.setObjectName(_fromUtf8("label_X"))
        self.label_5 = QtGui.QLabel(Panel)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 191, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_wavemeter_readout = QtGui.QLabel(Panel)
        self.label_wavemeter_readout.setGeometry(QtCore.QRect(60, 140, 90, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_wavemeter_readout.setFont(font)
        self.label_wavemeter_readout.setObjectName(_fromUtf8("label_wavemeter_readout"))
        self.checkBox_wavemeter = QtGui.QCheckBox(Panel)
        self.checkBox_wavemeter.setGeometry(QtCore.QRect(60, 111, 95, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.checkBox_wavemeter.setFont(font)
        self.checkBox_wavemeter.setObjectName(_fromUtf8("checkBox_wavemeter"))
        self.dsB_power = QtGui.QDoubleSpinBox(Panel)
        self.dsB_power.setGeometry(QtCore.QRect(225, 85, 53, 20))
        self.dsB_power.setObjectName(_fromUtf8("dsB_power"))
        self.label_power = QtGui.QLabel(Panel)
        self.label_power.setGeometry(QtCore.QRect(8, 85, 97, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_power.setFont(font)
        self.label_power.setObjectName(_fromUtf8("label_power"))
        self.dSBox_coarse_lambda = QtGui.QDoubleSpinBox(Panel)
        self.dSBox_coarse_lambda.setGeometry(QtCore.QRect(225, 59, 53, 20))
        self.dSBox_coarse_lambda.setObjectName(_fromUtf8("dSBox_coarse_lambda"))
        self.label_coarse_lambda = QtGui.QLabel(Panel)
        self.label_coarse_lambda.setGeometry(QtCore.QRect(8, 59, 130, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_coarse_lambda.setFont(font)
        self.label_coarse_lambda.setObjectName(_fromUtf8("label_coarse_lambda"))
        self.label = QtGui.QLabel(Panel)
        self.label.setGeometry(QtCore.QRect(9, 9, 54, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalSlider_p1 = QtGui.QSlider(Panel)
        self.horizontalSlider_p1.setGeometry(QtCore.QRect(9, 528, 231, 19))
        self.horizontalSlider_p1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_p1.setObjectName(_fromUtf8("horizontalSlider_p1"))
        self.doubleSpinBox_p1 = QtGui.QDoubleSpinBox(Panel)
        self.doubleSpinBox_p1.setGeometry(QtCore.QRect(271, 528, 53, 20))
        self.doubleSpinBox_p1.setObjectName(_fromUtf8("doubleSpinBox_p1"))
        self.label_curr_pos_readout_z = QtGui.QLabel(Panel)
        self.label_curr_pos_readout_z.setGeometry(QtCore.QRect(160, 440, 41, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_readout_z.setFont(font)
        self.label_curr_pos_readout_z.setObjectName(_fromUtf8("label_curr_pos_readout_z"))
        self.spinBox_Y = QtGui.QSpinBox(Panel)
        self.spinBox_Y.setGeometry(QtCore.QRect(90, 328, 51, 20))
        self.spinBox_Y.setObjectName(_fromUtf8("spinBox_Y"))
        self.spinBox_Z = QtGui.QSpinBox(Panel)
        self.spinBox_Z.setGeometry(QtCore.QRect(90, 360, 51, 20))
        self.spinBox_Z.setObjectName(_fromUtf8("spinBox_Z"))
        self.label_curr_pos_readout_y = QtGui.QLabel(Panel)
        self.label_curr_pos_readout_y.setGeometry(QtCore.QRect(100, 440, 41, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_readout_y.setFont(font)
        self.label_curr_pos_readout_y.setObjectName(_fromUtf8("label_curr_pos_readout_y"))
        self.radioButton_lowT = QtGui.QRadioButton(Panel)
        self.radioButton_lowT.setGeometry(QtCore.QRect(100, 620, 63, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.radioButton_lowT.setFont(font)
        self.radioButton_lowT.setObjectName(_fromUtf8("radioButton_lowT"))
        self.label_2 = QtGui.QLabel(Panel)
        self.label_2.setGeometry(QtCore.QRect(80, 450, 16, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_curr_pos_readout_x = QtGui.QLabel(Panel)
        self.label_curr_pos_readout_x.setGeometry(QtCore.QRect(40, 440, 41, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_readout_x.setFont(font)
        self.label_curr_pos_readout_x.setObjectName(_fromUtf8("label_curr_pos_readout_x"))
        self.label_curr_pos_text = QtGui.QLabel(Panel)
        self.label_curr_pos_text.setGeometry(QtCore.QRect(10, 410, 147, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_text.setFont(font)
        self.label_curr_pos_text.setObjectName(_fromUtf8("label_curr_pos_text"))
        self.spinBox_JPE_freq = QtGui.QSpinBox(Panel)
        self.spinBox_JPE_freq.setGeometry(QtCore.QRect(180, 230, 42, 22))
        self.spinBox_JPE_freq.setObjectName(_fromUtf8("spinBox_JPE_freq"))
        self.label_JPE_freq = QtGui.QLabel(Panel)
        self.label_JPE_freq.setGeometry(QtCore.QRect(20, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_JPE_freq.setFont(font)
        self.label_JPE_freq.setObjectName(_fromUtf8("label_JPE_freq"))
        self.label_rel_step_size = QtGui.QLabel(Panel)
        self.label_rel_step_size.setGeometry(QtCore.QRect(20, 260, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_rel_step_size.setFont(font)
        self.label_rel_step_size.setObjectName(_fromUtf8("label_rel_step_size"))
        self.spinBox_rel_step_size = QtGui.QSpinBox(Panel)
        self.spinBox_rel_step_size.setGeometry(QtCore.QRect(180, 260, 42, 22))
        self.spinBox_rel_step_size.setObjectName(_fromUtf8("spinBox_rel_step_size"))

        self.retranslateUi(Panel)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(_translate("Panel", "Panel", None))
        self.label_3.setText(_translate("Panel", ",", None))
        self.radioButton_roomT.setText(_translate("Panel", " room T", None))
        self.label_temperature.setText(_translate("Panel", "TEMPERATURE", None))
        self.pushButton_set_as_origin.setText(_translate("Panel", "Set as origin", None))
        self.label_Y.setText(_translate("Panel", "Y", None))
        self.label_11.setText(_translate("Panel", "FINE POSITIONING", None))
        self.label_Z.setText(_translate("Panel", "Z", None))
        self.pushButton_activate.setText(_translate("Panel", "Activate", None))
        self.label_X.setText(_translate("Panel", "X", None))
        self.label_5.setText(_translate("Panel", "COARSE POSITIONING", None))
        self.label_wavemeter_readout.setText(_translate("Panel", "#########", None))
        self.checkBox_wavemeter.setText(_translate("Panel", "wavemeter", None))
        self.label_power.setText(_translate("Panel", "power level [mW]", None))
        self.label_coarse_lambda.setText(_translate("Panel", "coarse wavelength [nm]", None))
        self.label.setText(_translate("Panel", "LASER", None))
        self.label_curr_pos_readout_z.setText(_translate("Panel", "###", None))
        self.label_curr_pos_readout_y.setText(_translate("Panel", "###", None))
        self.radioButton_lowT.setText(_translate("Panel", " low T", None))
        self.label_2.setText(_translate("Panel", ",", None))
        self.label_curr_pos_readout_x.setText(_translate("Panel", "###", None))
        self.label_curr_pos_text.setText(_translate("Panel", "current position (x,y,z):", None))
        self.label_JPE_freq.setText(_translate("Panel", "Step frequency (Hz)", None))
        self.label_rel_step_size.setText(_translate("Panel", "Relative step size (%)", None))

