# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_scan_panel.ui'
#
# Created: Mon Feb 22 19:35:23 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName(_fromUtf8("Panel"))
        Panel.resize(1017, 868)
        self.button_save = QtGui.QPushButton(Panel)
        self.button_save.setGeometry(QtCore.QRect(240, 460, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_save.setFont(font)
        self.button_save.setObjectName(_fromUtf8("button_save"))
        self.dsb_max_lambda = QtGui.QDoubleSpinBox(Panel)
        self.dsb_max_lambda.setGeometry(QtCore.QRect(640, 590, 62, 22))
        self.dsb_max_lambda.setObjectName(_fromUtf8("dsb_max_lambda"))
        self.sb_delay_msync = QtGui.QSpinBox(Panel)
        self.sb_delay_msync.setGeometry(QtCore.QRect(860, 560, 51, 22))
        self.sb_delay_msync.setObjectName(_fromUtf8("sb_delay_msync"))
        self.button_stop_pzscan = QtGui.QPushButton(Panel)
        self.button_stop_pzscan.setGeometry(QtCore.QRect(80, 740, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_stop_pzscan.setFont(font)
        self.button_stop_pzscan.setObjectName(_fromUtf8("button_stop_pzscan"))
        self.label_finescan = QtGui.QLabel(Panel)
        self.label_finescan.setGeometry(QtCore.QRect(300, 530, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_finescan.setFont(font)
        self.label_finescan.setObjectName(_fromUtf8("label_finescan"))
        self.button_start_long_scan = QtGui.QPushButton(Panel)
        self.button_start_long_scan.setGeometry(QtCore.QRect(520, 690, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_start_long_scan.setFont(font)
        self.button_start_long_scan.setObjectName(_fromUtf8("button_start_long_scan"))
        self.label_minV_finelaser = QtGui.QLabel(Panel)
        self.label_minV_finelaser.setGeometry(QtCore.QRect(300, 560, 46, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_minV_finelaser.setFont(font)
        self.label_minV_finelaser.setObjectName(_fromUtf8("label_minV_finelaser"))
        self.label_status = QtGui.QLabel(Panel)
        self.label_status.setGeometry(QtCore.QRect(460, 420, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_status.setFont(font)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.sb_mindelay_msync = QtGui.QSpinBox(Panel)
        self.sb_mindelay_msync.setGeometry(QtCore.QRect(850, 680, 61, 22))
        self.sb_mindelay_msync.setObjectName(_fromUtf8("sb_mindelay_msync"))
        self.label_sweep_msyncdelay = QtGui.QLabel(Panel)
        self.label_sweep_msyncdelay.setGeometry(QtCore.QRect(740, 650, 201, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_sweep_msyncdelay.setFont(font)
        self.label_sweep_msyncdelay.setObjectName(_fromUtf8("label_sweep_msyncdelay"))
        self.button_start_finelaser = QtGui.QPushButton(Panel)
        self.button_start_finelaser.setGeometry(QtCore.QRect(320, 680, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_start_finelaser.setFont(font)
        self.button_start_finelaser.setObjectName(_fromUtf8("button_start_finelaser"))
        self.sb_fine_tuning_steps_LRscan = QtGui.QSpinBox(Panel)
        self.sb_fine_tuning_steps_LRscan.setGeometry(QtCore.QRect(640, 650, 61, 22))
        self.sb_fine_tuning_steps_LRscan.setObjectName(_fromUtf8("sb_fine_tuning_steps_LRscan"))
        self.label_steps_pzscan = QtGui.QLabel(Panel)
        self.label_steps_pzscan.setGeometry(QtCore.QRect(60, 640, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_steps_pzscan.setFont(font)
        self.label_steps_pzscan.setObjectName(_fromUtf8("label_steps_pzscan"))
        self.sb_wait_cycles = QtGui.QSpinBox(Panel)
        self.sb_wait_cycles.setGeometry(QtCore.QRect(140, 670, 61, 22))
        self.sb_wait_cycles.setObjectName(_fromUtf8("sb_wait_cycles"))
        self.button_calibrate_finelaser = QtGui.QPushButton(Panel)
        self.button_calibrate_finelaser.setGeometry(QtCore.QRect(310, 740, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_calibrate_finelaser.setFont(font)
        self.button_calibrate_finelaser.setObjectName(_fromUtf8("button_calibrate_finelaser"))
        self.plot = LinePlot(Panel)
        self.plot.setGeometry(QtCore.QRect(50, 30, 921, 371))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.label_avg = QtGui.QLabel(Panel)
        self.label_avg.setGeometry(QtCore.QRect(230, 420, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_avg.setFont(font)
        self.label_avg.setObjectName(_fromUtf8("label_avg"))
        self.label_maxdelay_msync = QtGui.QLabel(Panel)
        self.label_maxdelay_msync.setGeometry(QtCore.QRect(740, 710, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_maxdelay_msync.setFont(font)
        self.label_maxdelay_msync.setObjectName(_fromUtf8("label_maxdelay_msync"))
        self.label_nr_steps_msyncdelay = QtGui.QLabel(Panel)
        self.label_nr_steps_msyncdelay.setGeometry(QtCore.QRect(740, 740, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_nr_steps_msyncdelay.setFont(font)
        self.label_nr_steps_msyncdelay.setObjectName(_fromUtf8("label_nr_steps_msyncdelay"))
        self.sb_avg = QtGui.QSpinBox(Panel)
        self.sb_avg.setGeometry(QtCore.QRect(320, 420, 42, 22))
        self.sb_avg.setObjectName(_fromUtf8("sb_avg"))
        self.lineEdit_fileName = QtGui.QLineEdit(Panel)
        self.lineEdit_fileName.setGeometry(QtCore.QRect(460, 460, 181, 20))
        self.lineEdit_fileName.setObjectName(_fromUtf8("lineEdit_fileName"))
        self.label_status_display = QtGui.QLabel(Panel)
        self.label_status_display.setGeometry(QtCore.QRect(510, 420, 461, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_status_display.setFont(font)
        self.label_status_display.setObjectName(_fromUtf8("label_status_display"))
        self.label_piezoscan = QtGui.QLabel(Panel)
        self.label_piezoscan.setGeometry(QtCore.QRect(60, 530, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_piezoscan.setFont(font)
        self.label_piezoscan.setObjectName(_fromUtf8("label_piezoscan"))
        self.label_mindelay_msync = QtGui.QLabel(Panel)
        self.label_mindelay_msync.setGeometry(QtCore.QRect(740, 680, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_mindelay_msync.setFont(font)
        self.label_mindelay_msync.setObjectName(_fromUtf8("label_mindelay_msync"))
        self.label_fileTag = QtGui.QLabel(Panel)
        self.label_fileTag.setGeometry(QtCore.QRect(400, 460, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_fileTag.setFont(font)
        self.label_fileTag.setObjectName(_fromUtf8("label_fileTag"))
        self.labelmaxV_pzscan = QtGui.QLabel(Panel)
        self.labelmaxV_pzscan.setGeometry(QtCore.QRect(60, 600, 46, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.labelmaxV_pzscan.setFont(font)
        self.labelmaxV_pzscan.setObjectName(_fromUtf8("labelmaxV_pzscan"))
        self.button_stop_sweepdelay = QtGui.QPushButton(Panel)
        self.button_stop_sweepdelay.setGeometry(QtCore.QRect(740, 810, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_stop_sweepdelay.setFont(font)
        self.button_stop_sweepdelay.setObjectName(_fromUtf8("button_stop_sweepdelay"))
        self.sb_nr_steps_finelaser = QtGui.QSpinBox(Panel)
        self.sb_nr_steps_finelaser.setGeometry(QtCore.QRect(370, 640, 61, 22))
        self.sb_nr_steps_finelaser.setObjectName(_fromUtf8("sb_nr_steps_finelaser"))
        self.label_max_lambda = QtGui.QLabel(Panel)
        self.label_max_lambda.setGeometry(QtCore.QRect(520, 590, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_max_lambda.setFont(font)
        self.label_max_lambda.setObjectName(_fromUtf8("label_max_lambda"))
        self.line = QtGui.QFrame(Panel)
        self.line.setGeometry(QtCore.QRect(30, 490, 951, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.button_resume_long_scan = QtGui.QPushButton(Panel)
        self.button_resume_long_scan.setGeometry(QtCore.QRect(620, 690, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_resume_long_scan.setFont(font)
        self.button_resume_long_scan.setObjectName(_fromUtf8("button_resume_long_scan"))
        self.dsb_minV_pzscan = QtGui.QDoubleSpinBox(Panel)
        self.dsb_minV_pzscan.setGeometry(QtCore.QRect(140, 560, 62, 22))
        self.dsb_minV_pzscan.setObjectName(_fromUtf8("dsb_minV_pzscan"))
        self.label_fine_tuning_steps = QtGui.QLabel(Panel)
        self.label_fine_tuning_steps.setGeometry(QtCore.QRect(520, 650, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_fine_tuning_steps.setFont(font)
        self.label_fine_tuning_steps.setObjectName(_fromUtf8("label_fine_tuning_steps"))
        self.dsb_minV_finelaser = QtGui.QDoubleSpinBox(Panel)
        self.dsb_minV_finelaser.setGeometry(QtCore.QRect(370, 560, 62, 22))
        self.dsb_minV_finelaser.setObjectName(_fromUtf8("dsb_minV_finelaser"))
        self.label_min_lambda = QtGui.QLabel(Panel)
        self.label_min_lambda.setGeometry(QtCore.QRect(520, 560, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_min_lambda.setFont(font)
        self.label_min_lambda.setObjectName(_fromUtf8("label_min_lambda"))
        self.cb_montana_sync = QtGui.QCheckBox(Panel)
        self.cb_montana_sync.setGeometry(QtCore.QRect(740, 530, 141, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cb_montana_sync.setFont(font)
        self.cb_montana_sync.setObjectName(_fromUtf8("cb_montana_sync"))
        self.label_nr_calib_pts = QtGui.QLabel(Panel)
        self.label_nr_calib_pts.setGeometry(QtCore.QRect(520, 620, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_nr_calib_pts.setFont(font)
        self.label_nr_calib_pts.setObjectName(_fromUtf8("label_nr_calib_pts"))
        self.label_minV_ps = QtGui.QLabel(Panel)
        self.label_minV_ps.setGeometry(QtCore.QRect(60, 560, 46, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_minV_ps.setFont(font)
        self.label_minV_ps.setObjectName(_fromUtf8("label_minV_ps"))
        self.sb_nr_repetitions = QtGui.QSpinBox(Panel)
        self.sb_nr_repetitions.setGeometry(QtCore.QRect(860, 620, 51, 22))
        self.sb_nr_repetitions.setObjectName(_fromUtf8("sb_nr_repetitions"))
        self.label_wait_cycles = QtGui.QLabel(Panel)
        self.label_wait_cycles.setGeometry(QtCore.QRect(60, 670, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_wait_cycles.setFont(font)
        self.label_wait_cycles.setObjectName(_fromUtf8("label_wait_cycles"))
        self.label_maxV__finelaser = QtGui.QLabel(Panel)
        self.label_maxV__finelaser.setGeometry(QtCore.QRect(300, 600, 46, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_maxV__finelaser.setFont(font)
        self.label_maxV__finelaser.setObjectName(_fromUtf8("label_maxV__finelaser"))
        self.label_delay_msync = QtGui.QLabel(Panel)
        self.label_delay_msync.setGeometry(QtCore.QRect(740, 560, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_delay_msync.setFont(font)
        self.label_delay_msync.setObjectName(_fromUtf8("label_delay_msync"))
        self.button_start_pzscan = QtGui.QPushButton(Panel)
        self.button_start_pzscan.setGeometry(QtCore.QRect(80, 710, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_start_pzscan.setFont(font)
        self.button_start_pzscan.setObjectName(_fromUtf8("button_start_pzscan"))
        self.label_nr_repetitions = QtGui.QLabel(Panel)
        self.label_nr_repetitions.setGeometry(QtCore.QRect(740, 620, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_nr_repetitions.setFont(font)
        self.label_nr_repetitions.setObjectName(_fromUtf8("label_nr_repetitions"))
        self.cb_autostop = QtGui.QCheckBox(Panel)
        self.cb_autostop.setGeometry(QtCore.QRect(90, 420, 101, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cb_autostop.setFont(font)
        self.cb_autostop.setObjectName(_fromUtf8("cb_autostop"))
        self.dsb_min_lambda = QtGui.QDoubleSpinBox(Panel)
        self.dsb_min_lambda.setGeometry(QtCore.QRect(640, 560, 62, 22))
        self.dsb_min_lambda.setObjectName(_fromUtf8("dsb_min_lambda"))
        self.button_stop_long_scan = QtGui.QPushButton(Panel)
        self.button_stop_long_scan.setGeometry(QtCore.QRect(570, 720, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_stop_long_scan.setFont(font)
        self.button_stop_long_scan.setObjectName(_fromUtf8("button_stop_long_scan"))
        self.label_nr_scans_msync = QtGui.QLabel(Panel)
        self.label_nr_scans_msync.setGeometry(QtCore.QRect(740, 590, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_nr_scans_msync.setFont(font)
        self.label_nr_scans_msync.setObjectName(_fromUtf8("label_nr_scans_msync"))
        self.label_nr_steps_finelaser = QtGui.QLabel(Panel)
        self.label_nr_steps_finelaser.setGeometry(QtCore.QRect(300, 640, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_nr_steps_finelaser.setFont(font)
        self.label_nr_steps_finelaser.setObjectName(_fromUtf8("label_nr_steps_finelaser"))
        self.button_start_sweepdelay = QtGui.QPushButton(Panel)
        self.button_start_sweepdelay.setGeometry(QtCore.QRect(740, 780, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_start_sweepdelay.setFont(font)
        self.button_start_sweepdelay.setObjectName(_fromUtf8("button_start_sweepdelay"))
        self.sb_nr_steps_pzscan = QtGui.QSpinBox(Panel)
        self.sb_nr_steps_pzscan.setGeometry(QtCore.QRect(140, 640, 61, 22))
        self.sb_nr_steps_pzscan.setObjectName(_fromUtf8("sb_nr_steps_pzscan"))
        self.label_longrangescan = QtGui.QLabel(Panel)
        self.label_longrangescan.setGeometry(QtCore.QRect(520, 530, 181, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_longrangescan.setFont(font)
        self.label_longrangescan.setObjectName(_fromUtf8("label_longrangescan"))
        self.sb_nr_calib_pts = QtGui.QSpinBox(Panel)
        self.sb_nr_calib_pts.setGeometry(QtCore.QRect(640, 620, 61, 22))
        self.sb_nr_calib_pts.setObjectName(_fromUtf8("sb_nr_calib_pts"))
        self.sb_maxdelay_msync = QtGui.QSpinBox(Panel)
        self.sb_maxdelay_msync.setGeometry(QtCore.QRect(850, 710, 61, 22))
        self.sb_maxdelay_msync.setObjectName(_fromUtf8("sb_maxdelay_msync"))
        self.button_stop_finelaser = QtGui.QPushButton(Panel)
        self.button_stop_finelaser.setGeometry(QtCore.QRect(320, 710, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_stop_finelaser.setFont(font)
        self.button_stop_finelaser.setObjectName(_fromUtf8("button_stop_finelaser"))
        self.sb_nr_scans_msync = QtGui.QSpinBox(Panel)
        self.sb_nr_scans_msync.setGeometry(QtCore.QRect(860, 590, 51, 22))
        self.sb_nr_scans_msync.setObjectName(_fromUtf8("sb_nr_scans_msync"))
        self.cb_autosave = QtGui.QCheckBox(Panel)
        self.cb_autosave.setGeometry(QtCore.QRect(90, 460, 101, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cb_autosave.setFont(font)
        self.cb_autosave.setObjectName(_fromUtf8("cb_autosave"))
        self.dsb_maxV_finelaser = QtGui.QDoubleSpinBox(Panel)
        self.dsb_maxV_finelaser.setGeometry(QtCore.QRect(370, 600, 62, 22))
        self.dsb_maxV_finelaser.setObjectName(_fromUtf8("dsb_maxV_finelaser"))
        self.dsb_maxV_pzscan = QtGui.QDoubleSpinBox(Panel)
        self.dsb_maxV_pzscan.setGeometry(QtCore.QRect(140, 600, 62, 22))
        self.dsb_maxV_pzscan.setObjectName(_fromUtf8("dsb_maxV_pzscan"))
        self.sb_nr_steps_msyncdelay = QtGui.QSpinBox(Panel)
        self.sb_nr_steps_msyncdelay.setGeometry(QtCore.QRect(850, 740, 61, 22))
        self.sb_nr_steps_msyncdelay.setObjectName(_fromUtf8("sb_nr_steps_msyncdelay"))

        self.retranslateUi(Panel)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(_translate("Panel", "Panel", None))
        self.button_save.setText(_translate("Panel", "SAVE", None))
        self.button_stop_pzscan.setText(_translate("Panel", "STOP", None))
        self.label_finescan.setText(_translate("Panel", "Fine Laser-Scan", None))
        self.button_start_long_scan.setText(_translate("Panel", "START", None))
        self.label_minV_finelaser.setText(_translate("Panel", "min V", None))
        self.label_status.setText(_translate("Panel", "status:", None))
        self.label_sweep_msyncdelay.setText(_translate("Panel", "Sweep Montana sync delay", None))
        self.button_start_finelaser.setText(_translate("Panel", "START", None))
        self.label_steps_pzscan.setText(_translate("Panel", "nr steps", None))
        self.button_calibrate_finelaser.setText(_translate("Panel", "CALIBRATE", None))
        self.label_avg.setText(_translate("Panel", "averaging:", None))
        self.label_maxdelay_msync.setText(_translate("Panel", "max delay (ms)", None))
        self.label_nr_steps_msyncdelay.setText(_translate("Panel", "nr steps", None))
        self.label_status_display.setText(_translate("Panel", "idle", None))
        self.label_piezoscan.setText(_translate("Panel", "JPE Piezo-Scan", None))
        self.label_mindelay_msync.setText(_translate("Panel", "min delay (ms)", None))
        self.label_fileTag.setText(_translate("Panel", "file tag:", None))
        self.labelmaxV_pzscan.setText(_translate("Panel", "max V", None))
        self.button_stop_sweepdelay.setText(_translate("Panel", "STOP", None))
        self.label_max_lambda.setText(_translate("Panel", "max lambda [nm]", None))
        self.button_resume_long_scan.setText(_translate("Panel", "RESUME", None))
        self.label_fine_tuning_steps.setText(_translate("Panel", "fine-tuning steps", None))
        self.label_min_lambda.setText(_translate("Panel", "min lambda [nm]", None))
        self.cb_montana_sync.setText(_translate("Panel", "Sync to Montana", None))
        self.label_nr_calib_pts.setText(_translate("Panel", "nr calibration pts", None))
        self.label_minV_ps.setText(_translate("Panel", "min V", None))
        self.label_wait_cycles.setText(_translate("Panel", "wait cycles", None))
        self.label_maxV__finelaser.setText(_translate("Panel", "max V", None))
        self.label_delay_msync.setText(_translate("Panel", "delay (ms)", None))
        self.button_start_pzscan.setText(_translate("Panel", "START", None))
        self.label_nr_repetitions.setText(_translate("Panel", "nr repetitions", None))
        self.cb_autostop.setText(_translate("Panel", "Auto-stop", None))
        self.button_stop_long_scan.setText(_translate("Panel", "STOP", None))
        self.label_nr_scans_msync.setText(_translate("Panel", "nr scans per sync", None))
        self.label_nr_steps_finelaser.setText(_translate("Panel", "nr steps", None))
        self.button_start_sweepdelay.setText(_translate("Panel", "START", None))
        self.label_longrangescan.setText(_translate("Panel", "Long-Range Laser Scan", None))
        self.button_stop_finelaser.setText(_translate("Panel", "STOP", None))
        self.cb_autosave.setText(_translate("Panel", "Auto-save", None))

from plots.chaco_plot import LinePlot
