# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperature_controller_v2.ui'
#
# Created: Wed Sep 23 15:30:33 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(230, 489)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        Form.setFont(font)
        self.label_set_T = QtGui.QLabel(Form)
        self.label_set_T.setGeometry(QtCore.QRect(10, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_set_T.setFont(font)
        self.label_set_T.setObjectName(_fromUtf8("label_set_T"))
        self.dsb_set_T = QtGui.QDoubleSpinBox(Form)
        self.dsb_set_T.setGeometry(QtCore.QRect(140, 40, 71, 21))
        self.dsb_set_T.setObjectName(_fromUtf8("dsb_set_T"))
        self.label_title = QtGui.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(40, 0, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.label_T_readout = QtGui.QLabel(Form)
        self.label_T_readout.setGeometry(QtCore.QRect(40, 80, 101, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(24)
        self.label_T_readout.setFont(font)
        self.label_T_readout.setObjectName(_fromUtf8("label_T_readout"))
        self.label_T_readout_2 = QtGui.QLabel(Form)
        self.label_T_readout_2.setGeometry(QtCore.QRect(140, 80, 101, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(24)
        self.label_T_readout_2.setFont(font)
        self.label_T_readout_2.setObjectName(_fromUtf8("label_T_readout_2"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 130, 221, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_title_2 = QtGui.QLabel(Form)
        self.label_title_2.setGeometry(QtCore.QRect(40, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_2.setFont(font)
        self.label_title_2.setObjectName(_fromUtf8("label_title_2"))
        self.label_T_min = QtGui.QLabel(Form)
        self.label_T_min.setGeometry(QtCore.QRect(10, 200, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_T_min.setFont(font)
        self.label_T_min.setObjectName(_fromUtf8("label_T_min"))
        self.dsb_set_T_min = QtGui.QDoubleSpinBox(Form)
        self.dsb_set_T_min.setGeometry(QtCore.QRect(140, 200, 71, 21))
        self.dsb_set_T_min.setObjectName(_fromUtf8("dsb_set_T_min"))
        self.dsb_set_T_max = QtGui.QDoubleSpinBox(Form)
        self.dsb_set_T_max.setGeometry(QtCore.QRect(140, 230, 71, 21))
        self.dsb_set_T_max.setObjectName(_fromUtf8("dsb_set_T_max"))
        self.label_set_T_max = QtGui.QLabel(Form)
        self.label_set_T_max.setGeometry(QtCore.QRect(10, 230, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_set_T_max.setFont(font)
        self.label_set_T_max.setObjectName(_fromUtf8("label_set_T_max"))
        self.dsb_set_nr_steps = QtGui.QDoubleSpinBox(Form)
        self.dsb_set_nr_steps.setGeometry(QtCore.QRect(140, 260, 71, 21))
        self.dsb_set_nr_steps.setObjectName(_fromUtf8("dsb_set_nr_steps"))
        self.label_set_nr_steps = QtGui.QLabel(Form)
        self.label_set_nr_steps.setGeometry(QtCore.QRect(10, 260, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_set_nr_steps.setFont(font)
        self.label_set_nr_steps.setObjectName(_fromUtf8("label_set_nr_steps"))
        self.dsb_set_dwell_time = QtGui.QDoubleSpinBox(Form)
        self.dsb_set_dwell_time.setGeometry(QtCore.QRect(140, 290, 71, 21))
        self.dsb_set_dwell_time.setObjectName(_fromUtf8("dsb_set_dwell_time"))
        self.label_set_dwell_time = QtGui.QLabel(Form)
        self.label_set_dwell_time.setGeometry(QtCore.QRect(10, 290, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_set_dwell_time.setFont(font)
        self.label_set_dwell_time.setObjectName(_fromUtf8("label_set_dwell_time"))
        self.pushButton_scan = QtGui.QPushButton(Form)
        self.pushButton_scan.setGeometry(QtCore.QRect(50, 330, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_scan.setFont(font)
        self.pushButton_scan.setObjectName(_fromUtf8("pushButton_scan"))
        self.pushButton_stop = QtGui.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(50, 380, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.pushButton_save = QtGui.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(50, 430, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_set_T.setText(_translate("Form", "set Temperature", None))
        self.label_title.setText(_translate("Form", "Crystal Temperature", None))
        self.label_T_readout.setText(_translate("Form", "#####", None))
        self.label_T_readout_2.setText(_translate("Form", "deg", None))
        self.label_title_2.setText(_translate("Form", "Scan Temperature", None))
        self.label_T_min.setText(_translate("Form", "T_min", None))
        self.label_set_T_max.setText(_translate("Form", "T_max", None))
        self.label_set_nr_steps.setText(_translate("Form", "nr steps", None))
        self.label_set_dwell_time.setText(_translate("Form", "dwell time [ms]", None))
        self.pushButton_scan.setText(_translate("Form", "SCAN", None))
        self.pushButton_stop.setText(_translate("Form", "STOP", None))
        self.pushButton_save.setText(_translate("Form", "SAVE", None))

