# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panel.ui'
#
# Created: Thu Apr 23 11:51:30 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(287, 593)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 16))

        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_coarse_lambda = QtGui.QLabel(Dialog)
        self.label_coarse_lambda.setGeometry(QtCore.QRect(20, 40, 151, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_coarse_lambda.setFont(font)
        self.label_coarse_lambda.setObjectName(_fromUtf8("label_coarse_lambda"))
        self.label_power = QtGui.QLabel(Dialog)
        self.label_power.setGeometry(QtCore.QRect(20, 100, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_power.setFont(font)
        self.label_power.setObjectName(_fromUtf8("label_power"))
        self.dSBox_coarse_lambda = QtGui.QDoubleSpinBox(Dialog)
        self.dSBox_coarse_lambda.setGeometry(QtCore.QRect(170, 40, 62, 22))
        self.dSBox_coarse_lambda.setObjectName(_fromUtf8("dSBox_coarse_lambda"))
        self.sB_power = QtGui.QSpinBox(Dialog)
        self.sB_power.setGeometry(QtCore.QRect(170, 100, 42, 22))
        self.sB_power.setObjectName(_fromUtf8("sB_power"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(220, 100, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 321, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.spinBox_X = QtGui.QSpinBox(Dialog)
        self.spinBox_X.setGeometry(QtCore.QRect(70, 250, 61, 22))
        self.spinBox_X.setObjectName(_fromUtf8("spinBox_X"))
        self.spinBox_Y = QtGui.QSpinBox(Dialog)
        self.spinBox_Y.setGeometry(QtCore.QRect(70, 280, 61, 22))
        self.spinBox_Y.setObjectName(_fromUtf8("spinBox_Y"))
        self.spinBox_Z = QtGui.QSpinBox(Dialog)
        self.spinBox_Z.setGeometry(QtCore.QRect(70, 310, 61, 22))
        self.spinBox_Z.setObjectName(_fromUtf8("spinBox_Z"))
        self.label_X = QtGui.QLabel(Dialog)
        self.label_X.setGeometry(QtCore.QRect(30, 250, 31, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_X.setFont(font)
        self.label_X.setObjectName(_fromUtf8("label_X"))
        self.label_Y = QtGui.QLabel(Dialog)
        self.label_Y.setGeometry(QtCore.QRect(30, 280, 31, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_Y.setFont(font)
        self.label_Y.setObjectName(_fromUtf8("label_Y"))
        self.label_Z = QtGui.QLabel(Dialog)
        self.label_Z.setGeometry(QtCore.QRect(30, 310, 31, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_Z.setFont(font)
        self.label_Z.setObjectName(_fromUtf8("label_Z"))
        self.pushButton_activate = QtGui.QPushButton(Dialog)
        self.pushButton_activate.setGeometry(QtCore.QRect(170, 260, 75, 23))
        self.pushButton_activate.setObjectName(_fromUtf8("pushButton_activate"))
        self.pushButton_set_as_origin = QtGui.QPushButton(Dialog)
        self.pushButton_set_as_origin.setGeometry(QtCore.QRect(170, 300, 75, 23))
        self.pushButton_set_as_origin.setObjectName(_fromUtf8("pushButton_set_as_origin"))
        self.label_curr_pos_text = QtGui.QLabel(Dialog)
        self.label_curr_pos_text.setGeometry(QtCore.QRect(10, 350, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_text.setFont(font)
        self.label_curr_pos_text.setObjectName(_fromUtf8("label_curr_pos_text"))
        self.label_curr_pos_readout = QtGui.QLabel(Dialog)
        self.label_curr_pos_readout.setGeometry(QtCore.QRect(140, 350, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_curr_pos_readout.setFont(font)
        self.label_curr_pos_readout.setObjectName(_fromUtf8("label_curr_pos_readout"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 400, 321, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalSlider_p1 = QtGui.QSlider(Dialog)
        self.horizontalSlider_p1.setGeometry(QtCore.QRect(30, 430, 160, 19))
        self.horizontalSlider_p1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_p1.setObjectName(_fromUtf8("horizontalSlider_p1"))
        self.horizontalSlider_p2 = QtGui.QSlider(Dialog)
        self.horizontalSlider_p2.setGeometry(QtCore.QRect(30, 460, 160, 19))
        self.horizontalSlider_p2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_p2.setObjectName(_fromUtf8("horizontalSlider_p2"))
        self.horizontalSlider_p3 = QtGui.QSlider(Dialog)
        self.horizontalSlider_p3.setGeometry(QtCore.QRect(30, 490, 160, 19))
        self.horizontalSlider_p3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_p3.setObjectName(_fromUtf8("horizontalSlider_p3"))
        self.checkBox_lock_piezos = QtGui.QCheckBox(Dialog)
        self.checkBox_lock_piezos.setGeometry(QtCore.QRect(210, 400, 41, 17))
        self.checkBox_lock_piezos.setObjectName(_fromUtf8("checkBox_lock_piezos"))
        self.doubleSpinBox_p1 = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_p1.setGeometry(QtCore.QRect(200, 430, 62, 22))
        self.doubleSpinBox_p1.setObjectName(_fromUtf8("doubleSpinBox_p1"))
        self.doubleSpinBox_p2 = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_p2.setGeometry(QtCore.QRect(200, 460, 62, 22))
        self.doubleSpinBox_p2.setObjectName(_fromUtf8("doubleSpinBox_p2"))
        self.doubleSpinBox_p3 = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_p3.setGeometry(QtCore.QRect(200, 490, 62, 22))
        self.doubleSpinBox_p3.setObjectName(_fromUtf8("doubleSpinBox_p3"))
        self.radioButton_lowT = QtGui.QRadioButton(Dialog)
        self.radioButton_lowT.setGeometry(QtCore.QRect(170, 550, 82, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.radioButton_lowT.setFont(font)
        self.radioButton_lowT.setObjectName(_fromUtf8("radioButton_lowT"))
        self.label_temperature = QtGui.QLabel(Dialog)
        self.label_temperature.setGeometry(QtCore.QRect(60, 560, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_temperature.setFont(font)
        self.label_temperature.setObjectName(_fromUtf8("label_temperature"))
        self.radioButton_roomT = QtGui.QRadioButton(Dialog)
        self.radioButton_roomT.setGeometry(QtCore.QRect(170, 570, 82, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.radioButton_roomT.setFont(font)
        self.radioButton_roomT.setObjectName(_fromUtf8("radioButton_roomT"))
        self.label_fine_laser_tuning = QtGui.QLabel(Dialog)
        self.label_fine_laser_tuning.setGeometry(QtCore.QRect(20, 70, 151, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_fine_laser_tuning.setFont(font)
        self.label_fine_laser_tuning.setObjectName(_fromUtf8("label_fine_laser_tuning"))
        self.sBox_fine_laser_tuning = QtGui.QSpinBox(Dialog)
        self.sBox_fine_laser_tuning.setGeometry(QtCore.QRect(170, 70, 42, 22))
        self.sBox_fine_laser_tuning.setObjectName(_fromUtf8("sBox_fine_laser_tuning"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(220, 70, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.checkBox_wavemeter = QtGui.QCheckBox(Dialog)
        self.checkBox_wavemeter.setGeometry(QtCore.QRect(60, 130, 121, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.checkBox_wavemeter.setFont(font)
        self.checkBox_wavemeter.setObjectName(_fromUtf8("checkBox_wavemeter"))
        self.label_wavemeter_readout = QtGui.QLabel(Dialog)
        self.label_wavemeter_readout.setGeometry(QtCore.QRect(70, 150, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.label_wavemeter_readout.setFont(font)
        self.label_wavemeter_readout.setObjectName(_fromUtf8("label_wavemeter_readout"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "LASER", None))
        self.label_coarse_lambda.setText(_translate("Dialog", "coarse wavelength [nm]", None))
        self.label_power.setText(_translate("Dialog", "power", None))
        self.label_4.setText(_translate("Dialog", "%", None))
        self.label_5.setText(_translate("Dialog", "COARSE POSITIONING", None))
        self.label_X.setText(_translate("Dialog", "X", None))
        self.label_Y.setText(_translate("Dialog", "Y", None))
        self.label_Z.setText(_translate("Dialog", "Z", None))
        self.pushButton_activate.setText(_translate("Dialog", "Activate", None))
        self.pushButton_set_as_origin.setText(_translate("Dialog", "Set as origin", None))
        self.label_curr_pos_text.setText(_translate("Dialog", "current position:", None))
        self.label_curr_pos_readout.setText(_translate("Dialog", "{##, ##, ##}", None))
        self.label_11.setText(_translate("Dialog", "FINE POSITIONING", None))
        self.checkBox_lock_piezos.setText(_translate("Dialog", "lock", None))
        self.radioButton_lowT.setText(_translate("Dialog", " low T", None))
        self.label_temperature.setText(_translate("Dialog", "Temperature:", None))
        self.radioButton_roomT.setText(_translate("Dialog", " room T", None))
        self.label_fine_laser_tuning.setText(_translate("Dialog", "fine tuning", None))
        self.label_14.setText(_translate("Dialog", "%", None))
        self.checkBox_wavemeter.setText(_translate("Dialog", "wavemeter", None))
        self.label_wavemeter_readout.setText(_translate("Dialog", "#########", None))

