# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scan_panel.ui'
#
# Created: Fri May 08 10:40:24 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

from measurement.lib.cavity.scan_gui_panels import MsgBox, ScanPlotCanvas


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(958, 660)
        self.plot_canvas = ScanPlotCanvas(parent=Form, width=900, height=320)
        self.plot_canvas.setGeometry(QtCore.QRect(20, 10, 921, 331))
        self.plot_canvas.setObjectName(_fromUtf8("graphicsView"))
        self.cb_autosave = QtGui.QCheckBox(Form)
        self.cb_autosave.setGeometry(QtCore.QRect(30, 360, 101, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cb_autosave.setFont(font)
        self.cb_autosave.setObjectName(_fromUtf8("cb_autosave"))
        self.cb_autostop = QtGui.QCheckBox(Form)
        self.cb_autostop.setGeometry(QtCore.QRect(150, 360, 101, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cb_autostop.setFont(font)
        self.cb_autostop.setObjectName(_fromUtf8("cb_autostop"))
        self.label_piezoscan = QtGui.QLabel(Form)
        self.label_piezoscan.setGeometry(QtCore.QRect(30, 410, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_piezoscan.setFont(font)
        self.label_piezoscan.setObjectName(_fromUtf8("label_piezoscan"))
        self.label_minV_ps = QtGui.QLabel(Form)
        self.label_minV_ps.setGeometry(QtCore.QRect(30, 440, 46, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_minV_ps.setFont(font)
        self.label_minV_ps.setObjectName(_fromUtf8("label_minV_ps"))
        self.dsb_minV_pzscan = QtGui.QDoubleSpinBox(Form)
        self.dsb_minV_pzscan.setGeometry(QtCore.QRect(100, 440, 62, 22))
        self.dsb_minV_pzscan.setObjectName(_fromUtf8("dsb_minV_pzscan"))
        self.dsb_maxV_pzscan = QtGui.QDoubleSpinBox(Form)
        self.dsb_maxV_pzscan.setGeometry(QtCore.QRect(100, 480, 62, 22))
        self.dsb_maxV_pzscan.setObjectName(_fromUtf8("dsb_maxV_pzscan"))
        self.labelmaxV_pzscan = QtGui.QLabel(Form)
        self.labelmaxV_pzscan.setGeometry(QtCore.QRect(30, 480, 46, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.labelmaxV_pzscan.setFont(font)
        self.labelmaxV_pzscan.setObjectName(_fromUtf8("labelmaxV_pzscan"))
        self.label_avg = QtGui.QLabel(Form)
        self.label_avg.setGeometry(QtCore.QRect(320, 360, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_avg.setFont(font)
        self.label_avg.setObjectName(_fromUtf8("label_avg"))
        self.sb_avg = QtGui.QSpinBox(Form)
        self.sb_avg.setGeometry(QtCore.QRect(400, 360, 42, 22))
        self.sb_avg.setObjectName(_fromUtf8("sb_avg"))
        self.label_steps_pzscan = QtGui.QLabel(Form)
        self.label_steps_pzscan.setGeometry(QtCore.QRect(30, 520, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_steps_pzscan.setFont(font)
        self.label_steps_pzscan.setObjectName(_fromUtf8("label_steps_pzscan"))
        self.sb_nr_steps_pzscan = QtGui.QSpinBox(Form)
        self.sb_nr_steps_pzscan.setGeometry(QtCore.QRect(100, 520, 42, 22))
        self.sb_nr_steps_pzscan.setObjectName(_fromUtf8("sb_nr_steps_pzscan"))
        self.dsb_minV_finelaser = QtGui.QDoubleSpinBox(Form)
        self.dsb_minV_finelaser.setGeometry(QtCore.QRect(340, 440, 62, 22))
        self.dsb_minV_finelaser.setObjectName(_fromUtf8("dsb_minV_finelaser"))
        self.sb_nr_steps_finelaser = QtGui.QSpinBox(Form)
        self.sb_nr_steps_finelaser.setGeometry(QtCore.QRect(340, 520, 42, 22))
        self.sb_nr_steps_finelaser.setObjectName(_fromUtf8("sb_nr_steps_finelaser"))
        self.label_finescan = QtGui.QLabel(Form)
        self.label_finescan.setGeometry(QtCore.QRect(270, 410, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_finescan.setFont(font)
        self.label_finescan.setObjectName(_fromUtf8("label_finescan"))
        self.dsb_maxV_finelaser = QtGui.QDoubleSpinBox(Form)
        self.dsb_maxV_finelaser.setGeometry(QtCore.QRect(340, 480, 62, 22))
        self.dsb_maxV_finelaser.setObjectName(_fromUtf8("dsb_maxV_finelaser"))
        self.label_nr_steps_finelaser = QtGui.QLabel(Form)
        self.label_nr_steps_finelaser.setGeometry(QtCore.QRect(270, 520, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_nr_steps_finelaser.setFont(font)
        self.label_nr_steps_finelaser.setObjectName(_fromUtf8("label_nr_steps_finelaser"))
        self.label_minV_finelaser = QtGui.QLabel(Form)
        self.label_minV_finelaser.setGeometry(QtCore.QRect(270, 440, 46, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_minV_finelaser.setFont(font)
        self.label_minV_finelaser.setObjectName(_fromUtf8("label_minV_finelaser"))
        self.label_maxV__finelaser = QtGui.QLabel(Form)
        self.label_maxV__finelaser.setGeometry(QtCore.QRect(270, 480, 46, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_maxV__finelaser.setFont(font)
        self.label_maxV__finelaser.setObjectName(_fromUtf8("label_maxV__finelaser"))
        self.dsb_max_lambda = QtGui.QDoubleSpinBox(Form)
        self.dsb_max_lambda.setGeometry(QtCore.QRect(610, 480, 62, 22))
        self.dsb_max_lambda.setObjectName(_fromUtf8("dsb_max_lambda"))
        self.dsb_min_lambda = QtGui.QDoubleSpinBox(Form)
        self.dsb_min_lambda.setGeometry(QtCore.QRect(610, 440, 62, 22))
        self.dsb_min_lambda.setObjectName(_fromUtf8("dsb_min_lambda"))
        self.label_min_lambda = QtGui.QLabel(Form)
        self.label_min_lambda.setGeometry(QtCore.QRect(490, 440, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_min_lambda.setFont(font)
        self.label_min_lambda.setObjectName(_fromUtf8("label_min_lambda"))
        self.label_max_lambda = QtGui.QLabel(Form)
        self.label_max_lambda.setGeometry(QtCore.QRect(490, 480, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_max_lambda.setFont(font)
        self.label_max_lambda.setObjectName(_fromUtf8("label_max_lambda"))
        self.label_longrangescan = QtGui.QLabel(Form)
        self.label_longrangescan.setGeometry(QtCore.QRect(490, 410, 181, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_longrangescan.setFont(font)
        self.label_longrangescan.setObjectName(_fromUtf8("label_longrangescan"))
        self.button_start_pzscan = QtGui.QPushButton(Form)
        self.button_start_pzscan.setGeometry(QtCore.QRect(50, 560, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_start_pzscan.setFont(font)
        self.button_start_pzscan.setObjectName(_fromUtf8("button_start_pzscan"))
        self.button_stop_pzscan = QtGui.QPushButton(Form)
        self.button_stop_pzscan.setGeometry(QtCore.QRect(50, 590, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_stop_pzscan.setFont(font)
        self.button_stop_pzscan.setObjectName(_fromUtf8("button_stop_pzscan"))
        self.button_stop_finelaser = QtGui.QPushButton(Form)
        self.button_stop_finelaser.setGeometry(QtCore.QRect(290, 590, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_stop_finelaser.setFont(font)
        self.button_stop_finelaser.setObjectName(_fromUtf8("button_stop_finelaser"))
        self.button_start_finelaser = QtGui.QPushButton(Form)
        self.button_start_finelaser.setGeometry(QtCore.QRect(290, 560, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_start_finelaser.setFont(font)
        self.button_start_finelaser.setObjectName(_fromUtf8("button_start_finelaser"))
        self.button_stop_long_scan = QtGui.QPushButton(Form)
        self.button_stop_long_scan.setGeometry(QtCore.QRect(530, 550, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_stop_long_scan.setFont(font)
        self.button_stop_long_scan.setObjectName(_fromUtf8("button_stop_long_scan"))
        self.button_start_long_scan = QtGui.QPushButton(Form)
        self.button_start_long_scan.setGeometry(QtCore.QRect(530, 520, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_start_long_scan.setFont(font)
        self.button_start_long_scan.setObjectName(_fromUtf8("button_start_long_scan"))
        self.button_save = QtGui.QPushButton(Form)
        self.button_save.setGeometry(QtCore.QRect(520, 360, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_save.setFont(font)
        self.button_save.setObjectName(_fromUtf8("button_save"))
        self.button_calibrate_finelaser = QtGui.QPushButton(Form)
        self.button_calibrate_finelaser.setGeometry(QtCore.QRect(280, 620, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_calibrate_finelaser.setFont(font)
        self.button_calibrate_finelaser.setObjectName(_fromUtf8("button_calibrate_finelaser"))
        self.pushButton_9 = QtGui.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(520, 580, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.label_timeseries = QtGui.QLabel(Form)
        self.label_timeseries.setGeometry(QtCore.QRect(760, 410, 181, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_timeseries.setFont(font)
        self.label_timeseries.setObjectName(_fromUtf8("label_timeseries"))
        self.sb_nr_steps_timeseries = QtGui.QSpinBox(Form)
        self.sb_nr_steps_timeseries.setGeometry(QtCore.QRect(840, 440, 82, 22))
        self.sb_nr_steps_timeseries.setObjectName(_fromUtf8("sb_nr_steps_timeseries"))
        self.label_nr_steps_timeseries = QtGui.QLabel(Form)
        self.label_nr_steps_timeseries.setGeometry(QtCore.QRect(760, 440, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_nr_steps_timeseries.setFont(font)
        self.label_nr_steps_timeseries.setObjectName(_fromUtf8("label_nr_steps_timeseries"))
        self.label_wait_cycles = QtGui.QLabel(Form)
        self.label_wait_cycles.setGeometry(QtCore.QRect(760, 470, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.label_wait_cycles.setFont(font)
        self.label_wait_cycles.setObjectName(_fromUtf8("label_wait_cycles"))
        self.sb_wait_cycles = QtGui.QSpinBox(Form)
        self.sb_wait_cycles.setGeometry(QtCore.QRect(840, 470, 42, 22))
        self.sb_wait_cycles.setObjectName(_fromUtf8("sb_wait_cycles"))
        self.button_stop_timeseries = QtGui.QPushButton(Form)
        self.button_stop_timeseries.setGeometry(QtCore.QRect(780, 540, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_stop_timeseries.setFont(font)
        self.button_stop_timeseries.setObjectName(_fromUtf8("button_stop_timeseries"))
        self.button_start_timeseries = QtGui.QPushButton(Form)
        self.button_start_timeseries.setGeometry(QtCore.QRect(780, 510, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.button_start_timeseries.setFont(font)
        self.button_start_timeseries.setObjectName(_fromUtf8("button_start_timeseries"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.cb_autosave.setText(_translate("Form", "Auto-save", None))
        self.cb_autostop.setText(_translate("Form", "Auto-stop", None))
        self.label_piezoscan.setText(_translate("Form", "Piezo-Scan", None))
        self.label_minV_ps.setText(_translate("Form", "min V", None))
        self.labelmaxV_pzscan.setText(_translate("Form", "max V", None))
        self.label_avg.setText(_translate("Form", "averaging:", None))
        self.label_steps_pzscan.setText(_translate("Form", "nr steps", None))
        self.label_finescan.setText(_translate("Form", "Fine Laser-Scan", None))
        self.label_nr_steps_finelaser.setText(_translate("Form", "nr steps", None))
        self.label_minV_finelaser.setText(_translate("Form", "min V", None))
        self.label_maxV__finelaser.setText(_translate("Form", "max V", None))
        self.label_min_lambda.setText(_translate("Form", "min lambda [nm]", None))
        self.label_max_lambda.setText(_translate("Form", "max lambda [nm]", None))
        self.label_longrangescan.setText(_translate("Form", "Long-Range Laser Scan", None))
        self.button_start_pzscan.setText(_translate("Form", "START", None))
        self.button_stop_pzscan.setText(_translate("Form", "STOP", None))
        self.button_stop_finelaser.setText(_translate("Form", "STOP", None))
        self.button_start_finelaser.setText(_translate("Form", "START", None))
        self.button_stop_long_scan.setText(_translate("Form", "STOP", None))
        self.button_start_long_scan.setText(_translate("Form", "START", None))
        self.button_save.setText(_translate("Form", "SAVE", None))
        self.button_calibrate_finelaser.setText(_translate("Form", "CALIBRATE", None))
        self.pushButton_9.setText(_translate("Form", "CALIBRATE", None))
        self.label_timeseries.setText(_translate("Form", "Timeseries [V]", None))
        self.label_nr_steps_timeseries.setText(_translate("Form", "nr steps", None))
        self.label_wait_cycles.setText(_translate("Form", "wait cycles", None))
        self.button_stop_timeseries.setText(_translate("Form", "STOP", None))
        self.button_start_timeseries.setText(_translate("Form", "START", None))

